/* Private trade attachments; only immutable storage paths are persisted. */
window.FT73=(()=>{
const $=id=>document.getElementById(id),uid=()=>window.ftCloudSession?.user?.id,bucket='fundedtrack-trade-images',E=window.FTProtection?.escape||window.ft66Escape;
const sessions=new Map();let individualOwner=null,viewerUser=null;
function signed(v){if(!Number.isFinite(v))throw Error('Revisá el importe.');const r=$('result').value;return r==='Loss'?-Math.abs(v):r==='Win'?Math.abs(v):v;}
function lots(raw){if(raw==null||String(raw).trim()==='')return null;const n=Number(String(raw).replace(',','.'));if(!Number.isFinite(n)||n<=0||n>1000000)throw Error('El lotaje debe ser mayor que cero.');return n;}
function rr(v){return String(v||'').trim().replace(/,/g,'.');}
function normalize(){const el=$('pnlInput');if(el.value!=='')el.value=signed(Number(el.value));}
function stateHTML(value='Bien'){return ['Bien','Ansioso','MOLESTO',...(!['Bien','Ansioso','MOLESTO'].includes(value)?[value]:[])].map(v=>'<option '+(v===value?'selected':'')+'>'+E(v)+'</option>').join('');}
function client(){if(!uid()||!window.ftCloud?.storage)throw Error('Iniciá sesión y conectate a Internet para subir capturas.');return window.ftCloud.storage.from(bucket);}
function validPath(ref){return ref?.path?.startsWith(uid()+'/')&&/^[\w-]+\/[\w-]+\.jpg$/.test(ref.path);}
async function url(ref){if(!validPath(ref))throw Error('La captura no pertenece a esta sesión.');const {data,error}=await client().createSignedUrl(ref.path,300);if(error)throw error;return data.signedUrl;}
function invalidate(key){const prev=sessions.get(key);if(prev){prev.dead=true;for(const x of prev.items)if(x.preview)URL.revokeObjectURL(x.preview);}sessions.delete(key);}
function mount(key,host,refs=[]){invalidate(key);const s={user:uid(),items:refs.map(ref=>({ref})),pending:false,dead:false};sessions.set(key,s);host.innerHTML='<label>Capturas de la operación <small>(opcional · hasta 3)</small><input type="file" accept="image/png,image/jpeg,image/webp" multiple data-pick></label><p class="sub">PNG, JPG o WebP. Se optimizan y guardan de forma privada. Requiere conexión.</p><div class="ft73-gallery"></div><p class="ft73-image-error" role="alert"></p>';s.host=host;paint(s);
 host.querySelector('[data-pick]').onchange=async e=>{const files=[...e.target.files];e.target.value='';if(s.pending||s.dead)return;s.pending=true;error(s,'');try{if(s.items.length+files.length>3)throw Error('Podés adjuntar hasta 3 capturas.');const processed=[];for(const f of files){if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>12000000)throw Error('Usá PNG, JPG o WebP de hasta 12 MB.');processed.push(await compress(f));}if(s.dead||s.user!==uid()){for(const p of processed)URL.revokeObjectURL(p.preview);return;}s.items.push(...processed);paint(s);}catch(ex){error(s,ex.message);}finally{s.pending=false;}};
 return s;
}
function error(s,msg){if(!s.dead)s.host.querySelector('.ft73-image-error').textContent=msg;}
async function compress(file){const object=URL.createObjectURL(file),img=new Image();try{await new Promise((ok,no)=>{img.onload=ok;img.onerror=()=>no(Error('No se pudo leer esa imagen.'));img.src=object;});if(img.width*img.height>40000000)throw Error('La imagen tiene demasiada resolución.');const scale=Math.min(1,1600/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);let blob;for(const quality of [.86,.7,.55,.4]){blob=await new Promise(ok=>c.toBlob(ok,'image/jpeg',quality));if(blob&&blob.size<=1000000)break;}if(!blob||blob.size>1000000)throw Error('La captura sigue siendo muy grande. Recortala antes de subir.');return {blob,name:file.name.slice(0,120),preview:URL.createObjectURL(blob)};}finally{URL.revokeObjectURL(object);}}
function paint(s){const gallery=s.host.querySelector('.ft73-gallery');gallery.replaceChildren();s.items.forEach((item,i)=>{const card=document.createElement('div'),im=document.createElement('img'),remove=document.createElement('button');card.className='ft73-shot';im.alt='Captura de la operación';remove.type='button';remove.className='btn';remove.textContent='Quitar';remove.onclick=()=>{if(s.pending)return;if(item.preview)URL.revokeObjectURL(item.preview);s.items.splice(i,1);paint(s);};card.append(im,remove);gallery.append(card);if(item.preview)im.src=item.preview;else url(item.ref).then(u=>{if(!s.dead&&s.user===uid()&&im.isConnected)im.src=u;}).catch(()=>{im.alt='Captura guardada · conectate para verla';});});}
async function prepare(key){const s=sessions.get(key);if(!s)return [];if(s.pending)throw Error('Esperá a que termine de preparar las capturas.');if(s.user!==uid()||s.dead)throw Error('La sesión cambió. Volvé a abrir la operación.');for(const item of s.items){if(item.ref)continue;const path=s.user+'/'+crypto.randomUUID()+'.jpg';const {error:err}=await client().upload(path,item.blob,{contentType:'image/jpeg',upsert:false});if(err)throw Error('No se pudo subir la captura. Revisá tu conexión y ejecutá el SQL de capturas en Supabase.');if(s.user!==uid()||s.dead)throw Error('La sesión cambió durante la subida.');item.ref={path,name:item.name,size:item.blob.size,mime:'image/jpeg'};}return s.items.map(item=>({...item.ref}));}
function readIndividual(){return {lots:lots($('ft73Lots').value),images:(sessions.get('individual')?.items||[]).map(i=>i.ref).filter(Boolean)};}
function load(record={}){$('ft84OtherAsset').hidden=$('ft84OtherLabel').hidden=$('asset').value!=='__other__';if(record.asset&&!Array.from($('asset').options).some(o=>o.value===record.asset))$('asset').add(new Option(record.asset,record.asset));if(record.asset)$('asset').value=record.asset;$('ft73Lots').value=record.lots??'';if(record.state==='FOMO')$('state').innerHTML=stateHTML('FOMO');else $('state').innerHTML=stateHTML(record.state||'Bien');mount('individual',$('ft73Images'),record.images||[]);normalize();individualOwner={user:uid(),account:activeId,phase:acc().phase,status:acc().status};}
function view(refs,title='Capturas de la operación'){viewerUser=uid();const d=$('ft73Viewer');d.querySelector('h3').textContent=title;const body=d.querySelector('.ft73-view-body');body.replaceChildren();d.showModal();const owner=uid();for(const ref of refs||[]){const img=document.createElement('img');img.alt='Cargando captura…';body.append(img);url(ref).then(u=>{if(uid()===owner&&d.open) {img.src=u;img.alt='Captura de la operación';}}).catch(()=>{img.replaceWith(document.createTextNode('No se pudo cargar la captura. Revisá tu conexión y la configuración de Supabase.'));});}}
function refsHTML(refs){return refs?.length?'<button type="button" class="btn" data-ft73-images="'+encodeURIComponent(JSON.stringify(refs))+'">Ver capturas ('+refs.length+')</button>':'';}
document.addEventListener('click',e=>{const b=e.target.closest('[data-ft73-images]');if(b)try{view(JSON.parse(decodeURIComponent(b.dataset.ft73Images)));}catch{}});
function init(){const form=$('form');$('asset').addEventListener('change',()=>{const other=$('asset').value==='__other__';$('ft84OtherAsset').hidden=$('ft84OtherLabel').hidden=!other;});$('result').addEventListener('change',normalize);$('pnlInput').addEventListener('change',normalize);const originalOpen=window.openModal;window.openModal=function(...args){const out=originalOpen.apply(this,args);if($('modal').classList.contains('show'))load();return out;};const submit=form.onsubmit;form.onsubmit=async e=>{e.preventDefault();if(form.dataset.busy==='1')return;const err=$('ft72TradeError');try{if($('asset').value==='__other__'){const custom=$('ft84OtherAsset').value.trim().toUpperCase();if(!custom||custom==='__OTHER__')throw Error('Escribí el nombre del activo.');if(!Array.from($('asset').options).some(o=>o.value===custom))$('asset').add(new Option(custom,custom));$('asset').value=custom;$('ft84OtherAsset').hidden=$('ft84OtherLabel').hidden=true;}normalize();const riskValue=Number($('risk').value);if(!Number.isFinite(riskValue)||riskValue<0||riskValue>100)throw Error('El riesgo debe estar entre 0 y 100%.');if(Number($('pnlInput').value)===0)$('result').value='BE';lots($('ft73Lots').value);$('rr').value=rr($('rr').value);if(!individualOwner||individualOwner.user!==uid()||individualOwner.account!==activeId||individualOwner.phase!==acc().phase||individualOwner.status!==acc().status)throw Error('La cuenta o la sesión cambió. Volvé a abrir el formulario.');const baseline=JSON.stringify(accounts),owner=uid();form.dataset.busy='1';form.querySelector('[type=submit]').disabled=true;await prepare('individual');if(owner!==uid()||baseline!==JSON.stringify(accounts)||individualOwner.account!==activeId)throw Error('Los datos cambiaron durante la subida. Revisá la operación y volvé a guardar.');submit(e);}catch(ex){err.textContent=ex.message;err.scrollIntoView({block:'nearest'});}finally{form.dataset.busy='0';form.querySelector('[type=submit]').disabled=false;}};
 const close=window.closeModal;window.closeModal=function(){invalidate('individual');return close();}; // Existing success calls its captured close function; session invalidation remains safe.
 $('ft73ViewerClose').onclick=()=>$('ft73Viewer').close();window.addEventListener('ft67SyncStatus',()=>{for(const [key,s] of sessions)if(s.user!==uid())invalidate(key);if(viewerUser!==uid()){$('ft73Viewer').close();$('ft73Viewer').querySelector('.ft73-view-body').replaceChildren();}});
}
return {signed,lots,rr,stateHTML,mount,invalidate,prepare,readIndividual,load,refsHTML,view,init};})();
