(function(){'use strict';
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),ease='cubic-bezier(.22,1,.36,1)',pages=document.getElementById('ftPages');if(!pages)return;
const hosts=[document.querySelector('.mobile-nav'),document.querySelector('.sidebar')].filter(Boolean),indicators=new Map();
for(const host of hosts){host.classList.add('jf96-nav');const marker=document.createElement('i');marker.className='jf96-nav-indicator';marker.setAttribute('aria-hidden','true');host.append(marker);indicators.set(host,marker);}
function place(){for(const [host,marker]of indicators){const active=host.querySelector('#ft82More[aria-expanded=true]')||[...host.querySelectorAll('button.ft-nav-current')].find(b=>b.getClientRects().length);if(!active||!host.getClientRects().length){marker.style.opacity='0';continue;}const h=host.getBoundingClientRect(),b=active.getBoundingClientRect();marker.style.width=b.width+'px';marker.style.height=b.height+'px';marker.style.transform='translate('+(b.left-h.left-host.clientLeft+host.scrollLeft)+'px,'+(b.top-h.top-host.clientTop+host.scrollTop)+'px)';marker.style.opacity='1';}}
let pending=0;function queuePlace(){if(pending)return;pending=requestAnimationFrame(()=>{pending=0;place();});}
for(const host of hosts){new MutationObserver(queuePlace).observe(host,{subtree:true,attributes:true,attributeFilter:['class']});if(window.ResizeObserver)new ResizeObserver(queuePlace).observe(host);host.addEventListener('scroll',queuePlace,{passive:true});}
window.addEventListener('resize',queuePlace,{passive:true});queuePlace();
const selectors=['.ft-home-mini strong','.ft60-metric:not(.ft60-context) > strong','.ft70-metrics strong','.ft76-metrics strong','.ft-account-choice > span strong','#ftHomeBalance','#ftHomePnl','#ftHomeDaily','#balance','#pnl','#winrate','#ft59TodayPnl','#ft59TodayCount'];
let counters=[],frame=0,entry=0,pageAnimations=[];
function remove(c){c.el.classList.remove('jf96-count-source');c.overlay.remove();}
function stop(){cancelAnimationFrame(frame);frame=0;counters.forEach(remove);counters=[];pageAnimations.forEach(a=>a.cancel());pageAnimations=[];}
function numericText(raw){const tokens=[];const re=/[+-]?\d[\d.,]*/g;let match;while((match=re.exec(raw))){const token=match[0].replace(/[.,]+$/,'');if(!token)continue;const dot=token.lastIndexOf('.'),comma=token.lastIndexOf(','),last=Math.max(dot,comma),sep=last<0?'':token[last],tail=last<0?0:token.length-last-1,decimal=last>=0&&((dot>=0&&comma>=0)||tail!==3)&&tail>0;const decimals=decimal?Math.min(tail,6):0,normal=decimal?token.slice(0,last).replace(/[.,]/g,'')+'.'+token.slice(last+1):token.replace(/[.,]/g,'');const value=Number(normal);if(!Number.isFinite(value))return null;const locale=decimal?(sep===','?'es-PY':'en-US'):(comma>=0?'en-US':dot>=0?'es-PY':'en-US');const formatter=new Intl.NumberFormat(locale,{minimumFractionDigits:decimals,maximumFractionDigits:decimals,useGrouping:token.includes(',')||token.includes('.')&&!decimal});tokens.push({start:match.index,end:match.index+token.length,value,formatter,plus:token.startsWith('+')});}return tokens.length?progress=>{let out='',last=0;for(const t of tokens){out+=raw.slice(last,t.start)+(t.plus?'+':'')+t.formatter.format(t.value*progress);last=t.end;}return out+raw.slice(last);}:null;}
function beginCounts(page){if(reduced.matches||document.hidden)return;const set=new Set(page.querySelectorAll(selectors.join(',')));for(const el of set){const raw=el.textContent,format=numericText(raw),r=el.getBoundingClientRect();if(!format||!r.width||r.bottom<0||r.top>innerHeight||el.closest('[hidden]'))continue;const style=getComputedStyle(el);if(style.visibility==='hidden'||style.display==='none')continue;const overlay=document.createElement('span');overlay.className='jf96-count-overlay';overlay.setAttribute('aria-hidden','true');for(const key of ['fontFamily','fontSize','fontWeight','fontStyle','lineHeight','letterSpacing','textAlign','color','whiteSpace','wordBreak','overflowWrap','textTransform'])overlay.style[key]=style[key];overlay.textContent=format(0);Object.assign(overlay.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});document.body.append(overlay);el.classList.add('jf96-count-source');counters.push({el,overlay,raw,format});if(counters.length>=16)break;}if(!counters.length)return;const start=performance.now();function tick(now){const t=Math.min(1,(now-start)/720),p=1-Math.pow(1-t,3);counters=counters.filter(c=>{if(t>=1||!c.el.isConnected||!c.el.classList.contains('jf96-count-source')||c.el.textContent!==c.raw){remove(c);return false;}const r=c.el.getBoundingClientRect();Object.assign(c.overlay.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});c.overlay.textContent=c.format(p);return true;});frame=counters.length?requestAnimationFrame(tick):0;}frame=requestAnimationFrame(tick);}
let active=document.querySelector('.ft-page.active')?.id;
function enter(page){stop();cancelAnimationFrame(entry);if(reduced.matches||document.hidden)return;pageAnimations.push(page.animate([{opacity:.2,transform:'translateY(14px)'},{opacity:1,transform:'translateY(0)'}],{duration:340,easing:ease}));entry=requestAnimationFrame(()=>beginCounts(page));for(const bar of page.querySelectorAll('[role=progressbar] > i,[role=progressbar] > span')){if(bar.style.width.includes('%'))pageAnimations.push(bar.animate([{transform:'scaleX(0)',transformOrigin:'left'},{transform:'scaleX(1)',transformOrigin:'left'}],{duration:720,easing:ease}));}}
new MutationObserver(()=>{const page=document.querySelector('.ft-page.active');if(page&&page.id!==active){active=page.id;enter(page);queuePlace();}}).observe(pages,{subtree:true,attributes:true,attributeFilter:['class']});
// A modal overlays the page: retire any temporary counters before showing it.
for(const modal of document.querySelectorAll('.modal,dialog'))new MutationObserver(()=>{if(modal.matches('.show,[open]')){stop();if(!reduced.matches){const box=modal.querySelector('.modalbox')||modal;box.animate([{opacity:0,transform:'translateY(14px) scale(.985)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:260,easing:ease});}}}).observe(modal,{attributes:true,attributeFilter:['class','open']});
document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(entry);stop();}});reduced.addEventListener('change',()=>{cancelAnimationFrame(entry);stop();queuePlace();});
window.JourFundMotion=Object.freeze({refresh:queuePlace});
})();
