(function(){'use strict';
const $=id=>document.getElementById(id);
let dialog=null,pending=null,pendingUser=null,loginResolve=null,working=false,lastFocus=null,epoch=0,loadedUser=null;
function client(){const c=window.ftCloud;if(!c)throw Error('No se pudo conectar con el servicio de seguridad.');return c;}
function user(){return window.ftCloudSession?.user?.id||null;}
function message(error){const s=String(error?.message||error||'');if(/invalid.*code|otp.*invalid|verification.*failed/i.test(s))return 'El código no es válido o venció. Probá con el próximo código.';if(/rate|too many|429/i.test(s))return 'Demasiados intentos. Esperá un minuto y probá de nuevo.';return s;}
function ensureDialog(){if(dialog)return;dialog=document.createElement('dialog');dialog.id='jfSecurityDialog';dialog.setAttribute('aria-labelledby','jfSecurityTitle');document.body.append(dialog);dialog.addEventListener('cancel',e=>{e.preventDefault();cancel();});}
function shell(title,content){ensureDialog();lastFocus=document.activeElement;dialog.innerHTML='<header><h2 id="jfSecurityTitle"></h2></header><div class="jf-security-content">'+content+'<p id="jfSecurityError" role="alert"></p></div>';$('jfSecurityTitle').textContent=title;if(!dialog.open)dialog.showModal();}
function showError(e){if($('jfSecurityError'))$('jfSecurityError').textContent=message(e);}
function clear(){if(dialog){dialog.close();dialog.replaceChildren();}pending=null;pendingUser=null;working=false;lastFocus?.focus?.();}
async function cancel(){if(working)return;const resolve=loginResolve;loginResolve=null;const factor=pending,owner=pendingUser;clear();if(factor&&owner===user())try{await client().auth.mfa.unenroll({factorId:factor});}catch{}if(resolve){resolve(false);await window.ftCloudSignOut?.();}}
function challengeForm(){return '<form id="jfSecurityVerify"><label>Código de tu aplicación autenticadora<input id="jfSecurityCode" type="text" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" minlength="6" maxlength="6" required></label><button class="btn primary" type="submit">Verificar y continuar</button></form><button type="button" class="btn" id="jfSecurityCancel">Cancelar</button>';}
async function verifiedFactors(c){const {data,error}=await c.auth.mfa.listFactors();if(error)throw error;return (data.all||data.totp||[]).filter(f=>f.status==='verified'&&f.factor_type==='totp');}
async function verify(factorId,code,c=client()){if(!/^[0-9]{6}$/.test(code))throw Error('Escribí el código de 6 dígitos.');const {data,error}=await c.auth.mfa.challengeAndVerify({factorId,code});if(error)throw error;return data;}
async function authorize(c,uid){
 const check=await c.auth.getUser();if(check.error)throw check.error;if(check.data.user?.id!==uid)throw Error('La sesión cambió. Iniciá sesión nuevamente.');
 const {data,error}=await c.auth.mfa.getAuthenticatorAssuranceLevel();if(error)throw error;
 if(data.nextLevel!=='aal2'||data.currentLevel==='aal2')return check.data.user;
 const factors=await verifiedFactors(c);if(!factors.length)throw Error('No se encontró una aplicación autenticadora verificada.');
 return new Promise(resolve=>{loginResolve=resolve;pendingUser=uid;shell('Verificación en dos pasos','<p>Confirmá tu identidad para abrir tus cuentas.</p><label>Aplicación<select id="jfSecurityFactor"></select></label>'+challengeForm());for(const f of factors)$('jfSecurityFactor').add(new Option(f.friendly_name||'Aplicación autenticadora',f.id));$('jfSecurityCancel').textContent='Cerrar sesión';$('jfSecurityCancel').onclick=cancel;$('jfSecurityVerify').onsubmit=async e=>{e.preventDefault();if(working)return;working=true;const button=e.target.querySelector('button');button.disabled=true;try{await verify($('jfSecurityFactor').value,$('jfSecurityCode').value.trim(),c);if(user()!==uid)throw Error('La sesión cambió.');loginResolve=null;clear();resolve(check.data.user);}catch(ex){showError(ex);working=false;button.disabled=false;}};$('jfSecurityCode').focus();});
}
async function refresh(){const card=$('jfSecurityCard');if(!card||!document.body.classList.contains('ft-ready')||!user())return;const uid=user(),token=++epoch;loadedUser=uid;try{const c=client(),factors=await verifiedFactors(c);const {data,error}=await c.rpc('jourfund_security_status');if(error)throw error;if(token!==epoch||user()!==uid)return;$('jfSecurityState').textContent=factors.length?'Verificación en dos pasos activada':'Verificación en dos pasos desactivada';$('jfSecurityEnable').hidden=!!factors.length;$('jfSecurityDisable').hidden=!factors.length;$('jfSecuritySessions').replaceChildren();for(const s of data.sessions||[]){const row=document.createElement('div');row.className='jf-security-session';const title=document.createElement('strong'),detail=document.createElement('small');const agent=String(s.agent||'Dispositivo');title.textContent=(s.current?'Este dispositivo · ':'')+(/iPhone|iPad/i.test(agent)?'Safari / iOS':/Android/i.test(agent)?'Android':/Edg/i.test(agent)?'Edge':/OPR/i.test(agent)?'Opera':/Firefox/i.test(agent)?'Firefox':/Chrome/i.test(agent)?'Chrome':agent.slice(0,60));const date=new Date(s.lastActiveAt);detail.textContent='Última actividad: '+(isNaN(date)?'sin información':date.toLocaleString());row.append(title,detail);$('jfSecuritySessions').append(row);}$('jfSecurityStatus').textContent='';loadedUser=uid;}catch(ex){if(token===epoch&&user()===uid)$('jfSecurityStatus').textContent=message(ex);}}
async function enable(){const uid=user();if(!uid||working)return;working=true;const button=$('jfSecurityEnable');button.disabled=true;try{const c=client(),list=await c.auth.mfa.listFactors();if(list.error)throw list.error;for(const f of list.data.all||[])if(f.status==='unverified'&&f.factor_type==='totp'&&f.friendly_name==='JourFund')await c.auth.mfa.unenroll({factorId:f.id});const {data,error}=await c.auth.mfa.enroll({factorType:'totp',friendlyName:'JourFund'});if(error)throw error;if(user()!==uid){await c.auth.mfa.unenroll({factorId:data.id});return;}pending=data.id;pendingUser=uid;working=false;shell('Proteger mi cuenta','<p>Escaneá el QR con una aplicación autenticadora. En este mismo teléfono, podés copiar la clave e ingresarla manualmente.</p><img id="jfSecurityQR" alt="QR para configurar tu aplicación autenticadora"><details><summary>Configurar con clave manual</summary><code id="jfSecuritySecret"></code><button type="button" class="btn" id="jfSecurityCopy">Copiar clave</button></details><label class="jf-security-backup"><input id="jfSecurityBackup" type="checkbox" required form="jfSecurityVerify">Guardé una copia privada de la clave para recuperar el acceso si pierdo el teléfono.</label><p class="sub">Al confirmar, las otras sesiones se cerrarán.</p>'+challengeForm());const qr=data.totp.qr_code;$('jfSecurityQR').src=qr.startsWith('data:image/svg+xml')?qr:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(qr);$('jfSecuritySecret').textContent=data.totp.secret;$('jfSecurityCopy').onclick=async()=>{try{await navigator.clipboard.writeText(data.totp.secret);$('jfSecurityCopy').textContent='Clave copiada';}catch{showError('No se pudo copiar. Seleccioná la clave manualmente.');}};$('jfSecurityCancel').onclick=cancel;$('jfSecurityVerify').onsubmit=async e=>{e.preventDefault();if(working||uid!==user())return;working=true;const submit=e.target.querySelector('button');submit.disabled=true;try{await verify(pending,$('jfSecurityCode').value.trim());pending=null;clear();await refresh();window.ft67Toast?.('Seguridad activada','Tu cuenta ahora requiere el código de tu aplicación autenticadora.');}catch(ex){showError(ex);working=false;submit.disabled=false;}};}catch(ex){$('jfSecurityStatus').textContent=message(ex);working=false;}finally{button.disabled=false;}}
async function disable(){const uid=user();if(!uid||working)return;try{const factors=await verifiedFactors(client());if(!factors.length){await refresh();return;}shell('Desactivar verificación en dos pasos','<p>Ingresá un código actual antes de retirar esta protección.</p><label>Aplicación<select id="jfSecurityFactor"></select></label>'+challengeForm());pendingUser=uid;for(const f of factors)$('jfSecurityFactor').add(new Option(f.friendly_name||'Aplicación autenticadora',f.id));$('jfSecurityVerify').querySelector('button').textContent='Verificar y desactivar';$('jfSecurityCancel').onclick=cancel;$('jfSecurityVerify').onsubmit=async e=>{e.preventDefault();if(working||uid!==user())return;working=true;const button=e.target.querySelector('button');button.disabled=true;try{const id=$('jfSecurityFactor').value;await verify(id,$('jfSecurityCode').value.trim());if(uid!==user())throw Error('La sesión cambió.');const {error}=await client().auth.mfa.unenroll({factorId:id});if(error)throw error;await client().auth.refreshSession();clear();await refresh();window.ft67Toast?.('Protección actualizada','La aplicación autenticadora seleccionada se desvinculó.');}catch(ex){showError(ex);working=false;button.disabled=false;}};}catch(ex){$('jfSecurityStatus').textContent=message(ex);}}
function mount(){const grid=$('ftPageMyAccount')?.querySelector('.ft94-grid');if(!grid||$('jfSecurityCard'))return;const card=document.createElement('section');card.id='jfSecurityCard';card.className='ft-quick-card';card.innerHTML='<div class="jf-security-heading"><span aria-hidden="true">◇</span><div><h3>Seguridad</h3><p class="sub">Protegé tu acceso y administrá tus sesiones.</p></div></div><p id="jfSecurityState">Consultando protección…</p><div class="ft-action-row"><button type="button" class="btn primary" id="jfSecurityEnable">Activar verificación en dos pasos</button><button type="button" class="btn" id="jfSecurityDisable" hidden>Desactivar verificación</button><button type="button" class="btn" id="jfSecurityPassword">Restablecer contraseña</button></div><details id="jfSecuritySessionDetails"><summary>Dispositivos con sesión abierta</summary><div id="jfSecuritySessions"></div><div class="ft-action-row"><button type="button" class="btn" id="jfSecurityRefresh">Actualizar sesiones</button><button type="button" class="btn" id="jfSecurityOthers">Cerrar otras sesiones</button><button type="button" class="btn red" id="jfSecurityAll">Cerrar todas las sesiones</button></div></details><p id="jfSecurityStatus" role="status" aria-live="polite"></p>';grid.insertBefore(card,$('ftSignOut'));$('jfSecurityEnable').onclick=enable;$('jfSecurityDisable').onclick=disable;$('jfSecurityRefresh').onclick=refresh;$('jfSecuritySessionDetails').ontoggle=()=>{if($('jfSecuritySessionDetails').open)refresh();};$('jfSecurityOthers').onclick=async()=>{const uid=user();if(!confirm('¿Cerrar las sesiones de los otros dispositivos? Este dispositivo seguirá conectado.'))return;const b=$('jfSecurityOthers');b.disabled=true;try{const {error}=await client().auth.signOut({scope:'others'});if(error)throw error;if(user()!==uid)return;await refresh();$('jfSecurityStatus').textContent='Las otras sesiones se cerraron.';}catch(ex){$('jfSecurityStatus').textContent=message(ex);}finally{b.disabled=false;}};$('jfSecurityAll').onclick=()=>{if(confirm('¿Cerrar sesión en todos los dispositivos, incluido este?'))window.ftCloudSignOut('global');};let passwordAt=0;$('jfSecurityPassword').onclick=async()=>{if(Date.now()-passwordAt<60000){$('jfSecurityStatus').textContent='Esperá un minuto antes de solicitar otro correo.';return;}const uid=user(),email=window.ftCloudSession?.user?.email;if(!email)return;const b=$('jfSecurityPassword');b.disabled=true;try{const {error}=await client().auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error;if(uid!==user())return;passwordAt=Date.now();$('jfSecurityStatus').textContent='Revisá tu correo para restablecer la contraseña.';}catch(ex){$('jfSecurityStatus').textContent=message(ex);}finally{b.disabled=false;}};refresh();}
window.JFSecurity={authorize,mount,refresh};
window.addEventListener('ft67SyncStatus',()=>{const uid=user();if(pendingUser&&pendingUser!==uid){const resolve=loginResolve;loginResolve=null;clear();resolve?.(false);}if(!uid){epoch++;loadedUser=null;if($('jfSecuritySessions'))$('jfSecuritySessions').replaceChildren();}else if(document.body.classList.contains('ft-ready')&&loadedUser!==uid)refresh();});
document.addEventListener('DOMContentLoaded',mount,{once:true});
})();
