const CACHE='fundedtrack-v113';
const SHELL=['./security.css?v=111','./security.js?v=111','./vendor/supabase-2.57.4.js','./risk-redesign.css?v=106','./risk-redesign.js?v=107','./statistics.css?v=105','./statistics-engine.js?v=105','./statistics.js?v=105','./accounts-compact.css?v=99','./accounts-compact.js?v=110','./settings-redesign.css?v=98','./settings-redesign.js?v=98','./language.js?v=97','./language.css?v=97','./navigation-motion.css?v=96','./navigation-motion.js?v=96','./my-account.css?v=94','./my-account.js?v=112','./mobile-home.css?v=93','./mobile-home.js?v=93','./market-favorites.css','./market-favorites.js','./forex-calendar.css','./forex-calendar.js','./auth-motion.css','./auth-motion.js','./mobile-navigation.css','./mobile-navigation.js','./owner-badge.css','./owner-badge.js?v=111','./account-delete.js','./accounts-overview.css','./accounts-overview.js?v=100','./weekly.css','./weekly.js','./tools.css','./tools-engine.js','./tools.js','./','./index.html','./manifest.webmanifest','./icon-192.png','./icon-512.png','./icon-maskable-512.png','./apple-touch-icon.png','./brand-icon.svg','./brand-icon.svg?v=92','./brand-mark.svg','./manifest.webmanifest?v=92','./auth-motion.css?v=92','./auth-motion.js?v=92','./icon-192.png?v=92','./icon-512.png?v=92','./icon-maskable-512.png?v=92','./apple-touch-icon.png?v=92','./auth-market.svg','./operations-scene.png','./accounts-scene.png','./withdrawals-scene.png','./objectives-scene.png','./settings-scene.png'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('fundedtrack-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{
 if(e.request.method!=='GET'||new URL(e.request.url).origin!==self.location.origin)return;
 e.respondWith(fetch(e.request).then(r=>{if(r.ok){const copy=r.clone();e.waitUntil(caches.open(CACHE).then(c=>c.put(e.request,copy)))}return r}).catch(()=>caches.match(e.request).then(r=>r||Response.error())));
});
self.addEventListener('push',event=>{let data={};try{data=event.data?.json()||{}}catch{}const allowed=['ftPageHome','ftPageOps','ftPageAccounts','ftPageWithdrawals','ftPageObjectives','ftPageSettings'];const page=allowed.includes(data.page)?data.page:'ftPageHome';
event.waitUntil(self.registration.showNotification(String(data.title||'JourFund').slice(0,120),{body:String(data.body||'Abrí tu diario para revisar el aviso.').slice(0,300),icon:new URL('./icon-192.png',self.registration.scope).href,badge:new URL('./icon-192.png',self.registration.scope).href,tag:String(data.tag||'fundedtrack').slice(0,180),data:{page,accountId:String(data.accountId||'').slice(0,100)}}));});
self.addEventListener('notificationclick',event=>{event.notification.close();const data=event.notification.data||{};const url=new URL('./',self.registration.scope);url.searchParams.set('ftNoticePage',data.page||'ftPageHome');if(data.accountId)url.searchParams.set('ftNoticeAccount',data.accountId);
event.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(async clients=>{for(const client of clients){if(new URL(client.url).origin===url.origin&&new URL(client.url).pathname.startsWith(new URL(self.registration.scope).pathname)){client.postMessage({type:'FT_NOTICE',...data});return client.focus();}}return self.clients.openWindow(url.href);}));});


