(function(){'use strict';
const C=window.ftProtectionCloud,P=window.FTProtection,E=P.escape,$=id=>document.getElementById(id);
const count=a=>({trades:(a.phases||[]).reduce((s,p)=>s+(p.trades||[]).length,0)+(a.pa?.trades||[]).length,withdrawals:(a.pa?.withdrawals||[]).length});
let current=null,user=null;
const dialog=document.createElement('dialog');dialog.id='ft79DeleteDialog';dialog.setAttribute('aria-labelledby','ft79DeleteTitle');dialog.innerHTML='<header><h3 id="ft79DeleteTitle">Eliminar cuentas</h3><button class="btn" type="button" id="ft79DeleteClose">Cerrar</button></header><div id="ft79DeleteReview"></div><p id="ft79DeleteError" role="alert"></p><footer><button class="btn" type="button" id="ft79DeleteCancel">Cancelar</button><button class="btn ft79-danger" type="button" id="ft79DeleteConfirm">Eliminar definitivamente</button></footer>';document.body.append(dialog);
function close(){dialog.close();current=null;$('ft79DeleteReview').replaceChildren();$('ft79DeleteError').textContent='';}
$('ft79DeleteClose').onclick=close;$('ft79DeleteCancel').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
function owner(state){const now=C.snapshot();if(!document.body.classList.contains('ft-ready')||now.userId!==window.ftCloudSession?.user?.id||now.userId!==state.userId||now.revision!==state.revision||JSON.stringify(now.accounts)!==JSON.stringify(state.accounts))throw Error('Los datos cambiaron. Cerrá esta ventana y seleccioná de nuevo las cuentas.');if(now.conflict)throw Error('Resolvé primero el conflicto de sincronización en Ajustes.');if(now.busy)throw Error('Esperá a que termine la sincronización.');return now;}
function open(ids,options={}){try{const state=options.state||C.snapshot();owner(state);const unique=[...new Set(ids)],chosen=state.accounts.filter(a=>unique.includes(a.id));if(!chosen.length||chosen.length!==unique.length)throw Error('No se encontraron todas las cuentas seleccionadas.');current={ids:unique,state,options};const stats=chosen.map(count),trades=stats.reduce((s,x)=>s+x.trades,0),withdrawals=stats.reduce((s,x)=>s+x.withdrawals,0),remaining=state.accounts.length-chosen.length;
$('ft79DeleteTitle').textContent=options.label||'Eliminar cuentas';$('ft79DeleteReview').innerHTML='<p>Vas a eliminar <strong>'+chosen.length+' cuenta'+(chosen.length===1?'':'s')+'</strong>, con <strong>'+trades+' operación'+(trades===1?'':'es')+'</strong> y <strong>'+withdrawals+' retiro'+(withdrawals===1?'':'s')+'</strong>.</p><ul>'+chosen.map(a=>'<li>'+E(a.nickname||a.program)+' · '+E(a.firm)+' · $'+E(a.capital)+' · '+E(a.id.slice(-4))+'</li>').join('')+'</ul><p>Se quitarán de la app y el cambio se sincronizará con tu usuario. Las otras cuentas y el catálogo de programas se conservan.</p><p class="sub">Se guardará un respaldo local antes de borrar. Los archivos de capturas no se borran del almacenamiento privado.</p>'+(remaining===0?'<p class="ft79-warning">La app necesita al menos una cuenta de referencia. Creá una cuenta fuera del grupo o dejá una sin seleccionar antes de eliminar.</p>':'');$('ft79DeleteConfirm').disabled=remaining===0;$('ft79DeleteError').textContent='';dialog.showModal();$('ft79DeleteCancel').focus();return true;
}catch(e){window.ft67Toast('No se pudo abrir',e.message,'error');return false;}}
$('ft79DeleteConfirm').onclick=()=>{const work=current;if(!work)return;try{owner(work.state);const candidate=P.clone(work.state.accounts).filter(a=>!work.ids.includes(a.id));if(!candidate.length)throw Error('Dejá al menos una cuenta de referencia.');P.validate(candidate);C.backup(work.state.accounts,'Antes de eliminar '+work.ids.length+' cuentas');owner(work.state);C.commit(candidate,owner(work.state));close();work.options.onSuccess?.();if(!work.options.onSuccess)window.FTMultiAccounts.openIndividual(activeId,'ftPageAccounts');window.ft67Toast('Cuentas eliminadas',work.ids.length+' eliminada'+(work.ids.length===1?'':'s')+'. '+(window.ft67SyncState?.mode==='synced'?'Sincronizado.':'Sincronizando…'),'saved');}catch(e){$('ft79DeleteError').textContent=e.message;}};
function session(){const uid=document.body.classList.contains('ft-ready')?window.ftCloudSession?.user?.id:null;if(uid!==user){user=uid;close();}}window.addEventListener('ft67SyncStatus',session);new MutationObserver(session).observe(document.body,{attributes:true,attributeFilter:['class']});session();window.FTAccountDeletion={open,count};
})();
