/* FundedTrack: deterministic calculations for linear contracts or fixed tick values.
   Rates and specifications are user inputs, not live broker data. */
(function(root){'use strict';
const fail=m=>{throw Error(m)},finite=(v,name,zero=false)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0||(!zero&&v===0)||v>1e15)fail('Revisá '+name+'.');return v;};
function parse(value){let s=String(value??'').trim().replace(/\s/g,'');if(!s)return NaN;if(s.includes(',')&&s.includes('.'))return NaN;if(!/^[-+]?\d*(?:[.,]\d+)?$/.test(s))return NaN;return Number(s.replace(',','.'));}
const clean=v=>Number(v.toPrecision(14));
function config(c){finite(c.contract,'el tamaño del contrato');finite(c.pip,'el tamaño del pip');finite(c.tick,'el tamaño del tick');finite(c.step,'el paso de lotaje');finite(c.min,'el lote mínimo');finite(c.max,'el lote máximo');if(c.min>c.max)fail('El lote mínimo supera el máximo.');if(Math.abs(c.min/c.step-Math.round(c.min/c.step))>1e-7)fail('El lote mínimo debe respetar el paso de lotaje.');if(c.method==='tick')finite(c.tickValue,'el valor del tick en la moneda de tu cuenta');else if(c.method==='contract')finite(c.fx,'la conversión de moneda');else fail('Elegí el método de cálculo.');return c;}
function factor(c){config(c);return c.method==='tick'?c.tickValue/c.tick:c.contract*c.fx;}
function costs(c,lots){return finite(c.feeLot??0,'la comisión por lote',true)*lots+finite(c.feeFixed??0,'el costo fijo',true);}
function volume(c,lots){finite(c.step,'el paso de lotaje');finite(c.min,'el lote mínimo');finite(c.max,'el lote máximo');if(c.min>c.max)fail('El lote mínimo supera el máximo.');if(Math.abs(c.min/c.step-Math.round(c.min/c.step))>1e-7)fail('El lote mínimo debe respetar el paso de lotaje.');finite(lots,'el lotaje');if(lots<c.min-1e-10||lots>c.max+1e-10)fail('El lotaje debe estar entre '+c.min+' y '+c.max+'.');const q=lots/c.step;if(Math.abs(q-Math.round(q))>1e-7*Math.max(1,Math.abs(q)))fail('El lotaje debe respetar el paso de '+c.step+'.');return lots;}
function price(v,name){return finite(v,name);}
function side(v){if(!['buy','sell'].includes(v))fail('Elegí Compra o Venta.');return v==='buy'?1:-1;}
function stopCheck(entry,stop,direction){price(entry,'el precio de entrada');price(stop,'el Stop Loss');const d=side(direction);if(d*(entry-stop)<=0)fail(direction==='buy'?'En Compra, el Stop Loss debe estar debajo de la entrada.':'En Venta, el Stop Loss debe estar encima de la entrada.');return Math.abs(entry-stop);}
function budget(balance,mode,risk){finite(balance,'el balance');finite(risk,'el riesgo');if(!['percent','cash'].includes(mode))fail('Elegí porcentaje o dinero.');if(mode==='percent'&&risk>100)fail('El riesgo no puede superar 100%.');const b=mode==='percent'?balance*risk/100:risk;if(b>balance)fail('El riesgo supera el balance ingresado.');return clean(b);}
function position(c,x){const b=budget(x.balance,x.mode,x.risk),distance=stopCheck(x.entry,x.stop,x.side),f=factor(c),fee=costs(c,1)-(c.feeFixed||0),fixed=c.feeFixed||0;if(b<=fixed)fail('El costo fijo consume todo el riesgo elegido.');const lossLot=distance*f+fee,raw=(b-fixed)/lossLot;const n=Math.floor((Math.min(raw,c.max)+1e-12)/c.step);let lots=clean(n*c.step);if(lots*lossLot+fixed>b+1e-8)lots=clean((n-1)*c.step);if(lots<c.min-1e-10)return {budget:b,raw,lots:null,distance,minRisk:clean(c.min*lossLot+fixed),reason:'El lote mínimo supera el riesgo elegido. Reducí la distancia al stop o revisá el contrato.'};volume(c,lots);return {budget:b,raw,lots,distance,pips:distance/c.pip,units:lots*c.contract,actualRisk:clean(lots*lossLot+fixed),riskPct:clean((lots*lossLot+fixed)/x.balance*100),limited:raw>c.max};}
function pip(c,x){const f=factor(c);volume(c,x.lots);finite(x.pips,'la cantidad de pips',true);return {oneLot:clean(c.pip*f),value:clean(c.pip*f*x.lots),movement:clean(c.pip*f*x.lots*x.pips),priceDistance:clean(x.pips*c.pip)};}
function pnl(c,x){const f=factor(c);volume(c,x.lots);price(x.entry,'el precio de entrada');price(x.exit,'el precio de salida');const direction=side(x.side),distance=(x.exit-x.entry)*direction,gross=distance*f*x.lots,fees=costs(c,x.lots);return {gross:clean(gross),net:clean(gross-fees),fees,move:clean(distance),pips:clean(distance/c.pip),roi: x.balance>0?clean((gross-fees)/x.balance*100):null};}
function levels(c,x){const f=factor(c);volume(c,x.lots);const d=side(x.side);price(x.entry,'el precio de entrada');const fees=costs(c,x.lots);let stop=x.stop,take=x.take;if(x.mode==='money'){finite(x.loss,'la pérdida elegida');finite(x.profit,'la ganancia elegida');if(x.loss<=fees)fail('La pérdida elegida debe superar los costos.');const rawStop=x.entry-d*(x.loss-fees)/(f*x.lots),rawTake=x.entry+d*(x.profit+fees)/(f*x.lots);stop=clean((d===1?Math.ceil(rawStop/c.tick-1e-9):Math.floor(rawStop/c.tick+1e-9))*c.tick);take=clean((d===1?Math.ceil(rawTake/c.tick-1e-9):Math.floor(rawTake/c.tick+1e-9))*c.tick);}else if(x.mode!=='price')fail('Elegí precios o dinero.');const distance=stopCheck(x.entry,stop,x.side);price(take,'el Take Profit');if(d*(take-x.entry)<=0)fail('El Take Profit debe estar del lado de la ganancia.');const risk=distance*f*x.lots+fees,reward=d*(take-x.entry)*f*x.lots-fees;if(reward<=0)fail('Los costos consumen la ganancia del Take Profit.');return {stop,take,risk:clean(risk),reward:clean(reward),rr:clean(reward/risk),stopPips:clean(distance/c.pip),takePips:clean(Math.abs(take-x.entry)/c.pip),fees};}
function margin(c,x){volume(c,x.lots);let margin,notional=null;if(x.mode==='fixed'){finite(x.fixed,'el margen por lote');margin=x.lots*x.fixed;}else{price(x.entry,'el precio de referencia');finite(c.contract,'el tamaño del contrato');finite(c.fx,'la conversión de la moneda cotizada');notional=x.lots*c.contract*x.entry*c.fx;if(x.mode==='leverage'){finite(x.leverage,'el apalancamiento');if(x.leverage<1)fail('El apalancamiento debe ser 1 o mayor.');margin=notional/x.leverage;}else if(x.mode==='percent'){finite(x.rate,'la tasa de margen');if(x.rate>100)fail('La tasa de margen no puede superar 100%.');margin=notional*x.rate/100;}else fail('Elegí el cálculo de margen.');}return {margin:clean(margin),notional:notional==null?null:clean(notional)};}
root.FTToolsEngine={parse,config,budget,position,pip,pnl,levels,margin};
})(globalThis);
