(function(){'use strict';
const $=id=>document.getElementById(id),E=window.FTProtection.escape,L=window.FTLedger;
const body=$('ftPageObjectives')?.querySelector('.ft-page-body');if(!body)return;
const card=document.createElement('section');card.id='ft76Weekly';card.className='ft-quick-card ft76-weekly';card.setAttribute('aria-labelledby','ft76Title');
body.querySelector('.ft70-toolbar').after(card);
let offset=0,user=null;
const cash=n=>new Intl.NumberFormat('es-PY',{style:'currency',currency:'USD',currencyDisplay:'narrowSymbol',maximumFractionDigits:2}).format(n),signed=n=>(n>0?'+':'')+cash(n),tone=n=>n<0?'red':n>0?'green':'';
const compact=n=>new Intl.NumberFormat('es-PY',{notation:'compact',maximumFractionDigits:1}).format(Math.abs(n)),chartCash=n=>Math.abs(n)>=1000?(n<0?'−':n>0?'+':'')+'$'+compact(n):signed(n);
const date=s=>new Date(s+'T12:00:00Z'),iso=d=>d.toISOString().slice(0,10),add=(s,n)=>{const d=date(s);d.setUTCDate(d.getUTCDate()+n);return iso(d);};
function week(day,n=0){const d=date(day),weekday=(d.getUTCDay()+6)%7,start=add(day,-weekday+n*7);return {start,end:add(start,6)};}
function summary(list,start,end,today){const days=Array.from({length:7},(_,i)=>({date:add(start,i),cents:0})),batches=new Map();let records=0;
for(const a of list){const stages=(a.phases||[]).map(p=>p.trades||[]).concat([a.pa?.trades||[]]);stages.forEach((ts,slot)=>ts.forEach((t,i)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(t.date||'')||t.date<start||t.date>end||t.date>today||!Number.isFinite(Number(t.pnl)))return;const cents=Math.round(Number(t.pnl)*100),key=list.length>1&&t.multiBatchId?'batch:'+t.multiBatchId+':'+t.date:a.id+':'+slot+':'+i;const b=batches.get(key)||{cents:0};b.cents+=cents;batches.set(key,b);days.find(d=>d.date===t.date).cents+=cents;records++;}));}
const values=[...batches.values()].map(b=>b.cents),wins=values.filter(n=>n>0),losses=values.filter(n=>n<0),total=values.reduce((s,n)=>s+n,0);return {pnl:total/100,count:values.length,wins:wins.length,losses:losses.length,be:values.length-wins.length-losses.length,winRate:values.length?wins.length/values.length*100:null,averageWin:wins.length?wins.reduce((s,n)=>s+n,0)/wins.length/100:null,averageLoss:losses.length?losses.reduce((s,n)=>s+n,0)/losses.length/100:null,records,days:days.map(d=>({date:d.date,pnl:d.cents/100}))};}
function scope(){const grouped=$('ftPageObjectives').classList.contains('ft70-group-mode'),id=body.querySelector('[data-group-select]')?.value,g=grouped?window.FTMultiAccounts.groups().find(g=>g.id===id):null;return {grouped,group:g,list:grouped?(g?.accounts||[]):[acc()].filter(Boolean)};}
function chart(s,today){const max=Math.max(1,...s.days.map(d=>Math.abs(d.pnl))),labels=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];return '<div class="ft76-chart" role="img" aria-label="Resultado neto por día de la semana"><div class="ft76-zero"></div>'+s.days.map((d,i)=>{const value=d.pnl,future=d.date>today,h=Math.abs(value)/max*63;return '<div class="ft76-day" title="'+E(d.date+': '+(future?'Sin datos futuros':signed(value)))+'"><div class="ft76-plot"><span class="ft76-value '+tone(value)+'" style="'+(value<0?'top:calc(50% + '+h+'px + 4px)':'bottom:calc(50% + '+h+'px + 4px)')+'">'+(future?'—':chartCash(value))+'</span><i class="ft76-bar '+(value<0?'negative':'positive')+'" style="height:'+h+'px;'+(value<0?'top:50%':'bottom:50%')+'"></i></div><span>'+labels[i]+'</span></div>';}).join('')+'</div>';}
function paint(){const next=document.body.classList.contains('ft-ready')?window.ftCloudSession?.user?.id:null;if(next!==user){user=next;offset=0;}if(!user){card.hidden=true;card.replaceChildren();return;}card.hidden=false;
const ctx=scope(),reference=ctx.list[0]||acc(),today=L.day(reference),range=week(today,offset),s=summary(ctx.list,range.start,range.end,today),label=ctx.grouped?ctx.group?.name||'Sin grupo':reference.nickname||reference.firm+' · '+cash(reference.capital),fmt=new Intl.DateTimeFormat('es-PY',{day:'numeric',month:'short',timeZone:'UTC'}),period=fmt.format(date(range.start))+' – '+fmt.format(date(range.end))+' '+range.end.slice(0,4),options=accounts.map(a=>'<option value="a:'+E(a.id)+'">'+E(a.nickname||a.firm+' · '+cash(a.capital)+' · '+a.id.slice(-4))+'</option>').join('')+window.FTMultiAccounts.groups().map(g=>'<option value="g:'+E(g.id)+'">Grupo · '+E(g.name)+'</option>').join('');
card.innerHTML='<div class="ft76-heading"><div><h3 id="ft76Title">Resumen semanal</h3><p>Tu actividad, con una mirada más clara.</p></div><label><span class="ft65-sr">Cuenta o grupo del resumen</span><select id="ft76Account">'+options+'</select></label></div><div class="ft76-controls"><button class="btn" type="button" id="ft76Previous" aria-label="Semana anterior">‹</button><strong>'+E(period)+'</strong><button class="btn" type="button" id="ft76Next" aria-label="Semana siguiente" '+(offset===0?'disabled':'')+'>›</button>'+(offset!==0?'<button class="btn" id="ft76Current" type="button">Esta semana</button>':'<span class="ft76-badge">Semana actual</span>')+'</div><div class="ft76-metrics">'+[['Resultado neto',signed(s.pnl),tone(s.pnl),'Solo operaciones'],['Operaciones',String(s.count),'',s.wins+' ganadas · '+s.losses+' perdidas'+(s.be?' · '+s.be+' neutras':'')],['Ganancia media',s.averageWin===null?'—':signed(s.averageWin),'green',s.winRate===null?'Sin operaciones':'Win rate '+s.winRate.toFixed(1).replace('.',',')+'%'],['Pérdida media',s.averageLoss===null?'—':signed(s.averageLoss),'red',s.averageLoss===null?'Sin pérdidas registradas':'Promedio de resultados negativos']].map(([title,val,cl,sub])=>'<div><span>'+title+'</span><strong class="'+cl+'">'+val+'</strong><small>'+sub+'</small></div>').join('')+'</div>'+(!s.count?'<p class="ft76-empty" role="status">No hay operaciones registradas en esta semana.</p>':'')+chart(s,today)+'<p class="ft76-note">'+E(label)+' · Todas las fases y PA. No incluye retiros.<br>'+(ctx.grouped?'Las operaciones vinculadas cuentan una vez; el resultado y los promedios suman sus cuentas. '+s.records+' registros individuales. Fechas según el servidor de '+E(reference.nickname||reference.program)+'.':'Fechas según el servidor de esta cuenta (UTC'+((reference.serverOffset??3)>=0?'+':'')+(reference.serverOffset??3)+').')+'</p>';
$('ft76Account').value=ctx.grouped?'g:'+(ctx.group?.id||''):'a:'+reference.id;
$('ft76Account').onchange=e=>{const v=e.target.value;if(v.startsWith('g:'))window.FTMultiAccounts.select(v.slice(2));else window.FTMultiAccounts.openIndividual(v.slice(2),'ftPageObjectives');paint();};
$('ft76Previous').onclick=()=>{offset--;paint();};$('ft76Next').onclick=()=>{if(offset<0){offset++;paint();}};$('ft76Current')?.addEventListener('click',()=>{offset=0;paint();});
}
const prev=window.render;window.render=function(){const result=prev.apply(this,arguments);paint();return result;};
const go=window.ftGo;window.ftGo=function(){const result=go.apply(this,arguments);paint();return result;};
new MutationObserver(paint).observe(body.querySelector('.ft70-group-view'),{childList:true});
new MutationObserver(paint).observe(document.body,{attributes:true,attributeFilter:['class']});
window.addEventListener('ft67SyncStatus',paint);setInterval(()=>{if($('ftPageObjectives').classList.contains('active'))paint();},60000);
window.FTWeekly={week,summary,paint};paint();
})();
