import {db,json,cors,checked,validSubscription,prefs,send,lockPayload} from '../_shared/core.ts';
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{headers:cors});if(req.method!=='POST')return json({error:'POST requerido'},405);
try{const bearer=req.headers.get('Authorization')?.match(/^Bearer (.+)$/)?.[1];if(!bearer)return json({error:'Iniciá sesión'},401);const {data,error}=await db.auth.getUser(bearer);if(error||!data.user)return json({error:'Sesión inválida'},401);const uid=data.user.id;const text=await req.text();if(text.length>12000)return json({error:'Solicitud demasiado grande'},413);const body=JSON.parse(text);const action=body.action;
if(action==='state'){const preferences=checked(await db.from('ft_notification_preferences').select('settings').eq('user_id',uid).maybeSingle()).data;const notifications=checked(await db.from('ft_notifications').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(100)).data;const device=body.endpoint?checked(await db.from('ft_push_subscriptions').select('id').eq('user_id',uid).eq('endpoint',body.endpoint).maybeSingle()).data:null;return json({publicKey:Deno.env.get('VAPID_PUBLIC_KEY'),settings:preferences?.settings||null,notifications,registered:!!device});}
if(action==='settings'){const settings=prefs(body.settings);const old=checked(await db.from('ft_notification_preferences').select('settings').eq('user_id',uid).maybeSingle()).data;checked(await db.from('ft_notification_preferences').upsert({user_id:uid,settings,...(!old?.settings?.enabled&&settings.enabled?{enabled_at:new Date().toISOString()}: {})},{onConflict:'user_id'}));return json({ok:true});}
if(action==='subscribe'){const s=validSubscription(body.subscription);const existing=checked(await db.from('ft_push_subscriptions').select('id,user_id').eq('endpoint',s.endpoint).maybeSingle()).data;if(existing&&existing.user_id!==uid)return json({error:'Desactivá las notificaciones de la cuenta anterior en este dispositivo.'},409);const count=checked(await db.from('ft_push_subscriptions').select('id',{count:'exact',head:true}).eq('user_id',uid)).count;if(!existing&&(count||0)>=5)return json({error:'Máximo 5 dispositivos por usuario'},409);checked(await db.from('ft_push_subscriptions').upsert({user_id:uid,...s},{onConflict:'endpoint'}));return json({ok:true});}
if(action==='unsubscribe'){checked(await db.from('ft_push_subscriptions').delete().eq('user_id',uid).eq('endpoint',body.endpoint));return json({ok:true});}
if(action==='read'){let query=db.from('ft_notifications').update({read_at:new Date().toISOString()}).eq('user_id',uid).is('read_at',null);if(typeof body.eventKey==='string')query=query.eq('event_key',body.eventKey);checked(await query);return json({ok:true});}
if(action==='test'){const s=checked(await db.from('ft_push_subscriptions').select('endpoint,keys').eq('user_id',uid).eq('endpoint',body.endpoint).maybeSingle()).data;if(!s)return json({error:'Activá este dispositivo primero'},409);const allowed=checked(await db.rpc('ft_allow_push_test',{uid})).data;if(!allowed)return json({error:'Esperá un minuto antes de otra prueba'},429);const status=await send(s,lockPayload({title:'Notificaciones listas',body:'Este es un aviso de prueba. Abrí FundedTrack para revisar tu diario.',event_key:'test',page:'ftPageSettings'}));if(status===404||status===410)checked(await db.from('ft_push_subscriptions').delete().eq('user_id',uid).eq('endpoint',s.endpoint));return json(status>=200&&status<300?{ok:true}:{error:'El servicio push rechazó el envío; volvé a activar este dispositivo.'},status>=200&&status<300?200:502);}
return json({error:'Acción inválida'},400);
}catch(e){console.error('push-api failure',e instanceof Error?e.message:'unknown');return json({error:'No se pudo completar la operación. Revisá la configuración de notificaciones en Supabase.'},400);}});
