import '../_shared/rules.js';import '../_shared/events.js';import '../_shared/planner.js';
import {calendarState} from '../_shared/calendar.ts';
import {db,json as responseJson,corsFor,allowedOrigin,checked,validSubscription,prefs,send,lockPayload} from '../_shared/core.ts';
Deno.serve(async req=>{const headers=corsFor(req),json=(value:unknown,status=200)=>responseJson(value,status,headers);if(!allowedOrigin(req.headers.get('Origin')))return json({error:'Origen no permitido'},403);if(req.method==='OPTIONS')return new Response(null,{headers});if(req.method!=='POST')return json({error:'POST requerido'},405);
try{const bearer=req.headers.get('Authorization')?.match(/^Bearer (.+)$/)?.[1];if(!bearer)return json({error:'Iniciá sesión'},401);const {data,error}=await db.auth.getUser(bearer);if(error||!data.user)return json({error:'Sesión inválida'},401);const uid=data.user.id;const announced=Number(req.headers.get('content-length')||0);if(announced>32000)return json({error:'Solicitud demasiado grande'},413);const reader=req.body?.getReader();if(!reader)return json({error:'Solicitud vacía'},400);const chunks:Uint8Array[]=[];let bytes=0;while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>32000){await reader.cancel();return json({error:'Solicitud demasiado grande'},413);}chunks.push(value);}const raw=new Uint8Array(bytes);let offset=0;for(const chunk of chunks){raw.set(chunk,offset);offset+=chunk.byteLength;}let body:any;try{body=JSON.parse(new TextDecoder().decode(raw));}catch{return json({error:'JSON inválido'},400);}if(!body||typeof body!=='object'||Array.isArray(body))return json({error:'Solicitud inválida'},400);const action=body.action;let claims:any;try{claims=JSON.parse(atob(bearer.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));}catch{return json({error:'Sesión inválida'},401);}if(typeof claims.session_id!=='string'||!/^[a-f0-9-]{36}$/i.test(claims.session_id))return json({error:'Sesión inválida'},401);const access=checked(await db.rpc('jourfund_authorize_request',{uid,sid:claims.session_id,assurance:claims.aal||'aal1',request_bucket:action==='state'?'push-read':'push-write'})).data;if(access!=='ok')return json({error:access==='mfa'?'Completá la verificación en dos pasos.':access==='rate'?'Demasiadas solicitudes. Esperá un minuto.':'La sesión venció. Iniciá sesión nuevamente.'},access==='rate'?429:access==='mfa'?403:401);
if(action==='state'){const preferences=checked(await db.from('ft_notification_preferences').select('settings').eq('user_id',uid).maybeSingle()).data;const notifications=checked(await db.from('ft_notifications').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(100)).data;const device=body.endpoint?checked(await db.from('ft_push_subscriptions').select('id').eq('user_id',uid).eq('endpoint',body.endpoint).maybeSingle()).data:null;const actions=checked(await db.from('ft_notice_actions').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(500)).data;return json({version:64,publicKey:Deno.env.get('VAPID_PUBLIC_KEY'),settings:preferences?.settings||null,notifications,actions,calendar:await calendarState(),registered:!!device});}
if(action==='settings'){const old=checked(await db.from('ft_notification_preferences').select('settings').eq('user_id',uid).maybeSingle()).data;const settings=prefs({...old?.settings,...body.settings});checked(await db.from('ft_notification_preferences').upsert({user_id:uid,settings,...(!old?.settings?.enabled&&settings.enabled?{enabled_at:new Date().toISOString()}: {})},{onConflict:'user_id'}));return json({ok:true});}
if(action==='handle'){if(!['complete','snooze'].includes(body.mode)||typeof body.eventKey!=='string'||body.eventKey.length>400)return json({error:'Acción inválida'},400);const notice=checked(await db.from('ft_notifications').select('id,kind').eq('user_id',uid).eq('event_key',body.eventKey).maybeSingle()).data;if(!notice)return json({error:'Esperá a que el aviso se sincronice con el servidor.'},409);if(!['custom','reminder','sessions','news','newsBefore'].includes(notice.kind)||body.mode==='snooze'&&!['custom','reminder','sessions'].includes(notice.kind))return json({error:'Este aviso no se puede posponer.'},400);checked(await db.from('ft_notice_actions').upsert({user_id:uid,event_key:body.eventKey,mode:body.mode,until_at:body.mode==='snooze'?new Date(Date.now()+15*60000).toISOString():null,revision:crypto.randomUUID(),created_at:new Date().toISOString()},{onConflict:'user_id,event_key'}));checked(await db.from('ft_notifications').update({read_at:new Date().toISOString()}).eq('user_id',uid).eq('id',notice.id));checked(await db.from('ft_push_deliveries').delete().eq('notification_id',notice.id).is('delivered_at',null));return json({ok:true});}
if(action==='subscribe'){const s=validSubscription(body.subscription);const existing=checked(await db.from('ft_push_subscriptions').select('id,user_id').eq('endpoint',s.endpoint).maybeSingle()).data;if(existing&&existing.user_id!==uid)return json({error:'Desactivá las notificaciones de la cuenta anterior en este dispositivo.'},409);const count=checked(await db.from('ft_push_subscriptions').select('id',{count:'exact',head:true}).eq('user_id',uid)).count;if(!existing&&(count||0)>=5)return json({error:'Máximo 5 dispositivos por usuario'},409);checked(await db.from('ft_push_subscriptions').upsert({user_id:uid,...s},{onConflict:'endpoint'}));return json({ok:true});}
if(action==='unsubscribe'){checked(await db.from('ft_push_subscriptions').delete().eq('user_id',uid).eq('endpoint',body.endpoint));return json({ok:true});}
if(action==='read'){let query=db.from('ft_notifications').update({read_at:new Date().toISOString()}).eq('user_id',uid).is('read_at',null);if(typeof body.eventKey==='string')query=query.eq('event_key',body.eventKey);checked(await query);return json({ok:true});}
if(action==='test'){const s=checked(await db.from('ft_push_subscriptions').select('endpoint,keys').eq('user_id',uid).eq('endpoint',body.endpoint).maybeSingle()).data;if(!s)return json({error:'Activá este dispositivo primero'},409);const allowed=checked(await db.rpc('ft_allow_push_test',{uid})).data;if(!allowed)return json({error:'Esperá un minuto antes de otra prueba'},429);const status=await send(s,lockPayload({title:'Notificaciones listas',body:'Este es un aviso de prueba. Abrí FundedTrack para revisar tu diario.',event_key:'test',page:'ftPageSettings'}));if(status===404||status===410)checked(await db.from('ft_push_subscriptions').delete().eq('user_id',uid).eq('endpoint',s.endpoint));return json(status>=200&&status<300?{ok:true}:{error:'El servicio push rechazó el envío; volvé a activar este dispositivo.'},status>=200&&status<300?200:502);}
return json({error:'Acción inválida'},400);
}catch(e){console.error('push-api failure',e instanceof Error?e.message:'unknown');return json({error:'No se pudo completar la operación. Revisá la configuración de notificaciones en Supabase.'},400);}});
